services:
  mysql:
    image: mysql:8.4
    container_name: logistics-network-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: logistics_network
    ports:
      - "3306:3306"
    volumes:
      - logistics_mysql_data:/var/lib/mysql

volumes:
  logistics_mysql_data:
